Fly:
  groups:
    # ORDER MUST BE IN REVERSE (LONGEST DURATION TO SHORTEST DURATION)
    # Permission: cubicice.fly.<group> (Players will still need cubicice.fly permission in order to use the Fly Ticket)
    # Time format: <integer>[h/m/s]
    spikes: 20h
    frozen: 12h
    blizzard: 6h
    yeti: 3h
    polar: 1h
    north: 30m

Anti_AFK:
  Check:
    interval: 60
    tolerance: 5
  Station:
    world: xxxxxxxxxx
    x: 0000000000
    y: 0000000000
    z: 0000000000
    yaw: 0000000000
    pitch: 0000000000
    radius: 8

MySQL:
  Hostname: 0000000000
  Port: 0000000000
  Database: xxxxxxxxxx
  Username: xxxxxxxxxx
  Password: xxxxxxxxxx

GuildID: 437845027150888960
StaffChatChannelID: 807970487120560158
TicketCategoryID: 814676580840374292
StaffRoleID: 735125526951493792
DonateInformationChannelID: 1190296645955506186